In [1]:
import pandas as pd
import requests
from census import Census

from config import api_key

c = Census(api_key, year=2017)
print(api_key)

85ac64b6b5a9c0901b00329d1ef41f0c53ccfc98

In [5]:
census_data = c.acs5.get(("NAME", "B19013_001E", "B01003_001E", "B01002_001E",
                          "B19301_001E","B23025_002E","B25058_001E","B08301_001E","B08301_003E","B08301_010E","B15003_002E","B15003_018E","B15003_017E",
                          "B15003_022E","B15003_021E","B15003_023E","B15003_024E","B15003_025E","B08101_041E",
                          "B17001_002E"), geo={'for': 'tract:*','in': 'state:17 county:031'})

census_pd = pd.DataFrame(census_data)

census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B01002_001E": "Median Age",
                                      "B19013_001E": "Household Income",
                                      "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      'B23025_002E': "Employed Population",
                                      "B25058_001E": "Median Contract Rent",
                                      "B08301_001E": "Means of transport",
                                      'B08301_003E': "Means of transport (Auto)",
                                      "B08301_010E": "Means of transport (Public)",
                                      "B08101_041E": "Means of transport (Other)",
                                      "B15003_002E": "No Education",
                                      "B15003_017E": "High School",
                                      "B15003_018E": "GED",
                                      "B15003_022E": "Bachelors",
                                      "B15003_021E": "Some College",
                                      "B15003_023E": "Masters",
                                      "B15003_024E": "Professional",
                                      "B15003_025E": "Doctorate",
                                      "NAME": "Name"})
print(len(census_pd))
census_pd.head()

1319

,Median Age,Population,Means of transport (Other),Means of transport,Means of transport (Auto),Means of transport (Public),No Education,High School,GED,Some College,...,Doctorate,Poverty Count,Household Income,Per Capita Income,Employed Population,Median Contract Rent,Name,county,state,tract
0,44.0,5541.0,30.0,2878.0,2232.0,366.0,0.0,710.0,197.0,470.0,...,76.0,99.0,84863.0,39199.0,3112.0,827.0,"Census Tract 5610, Cook County, Illinois",031,17,561000
1,33.0,1600.0,17.0,790.0,357.0,188.0,4.0,350.0,39.0,142.0,...,3.0,161.0,57045.0,26001.0,855.0,911.0,"Census Tract 6401, Cook County, Illinois",031,17,640100
2,28.0,6464.0,13.0,2892.0,1469.0,431.0,327.0,1300.0,72.0,196.0,...,0.0,1285.0,44063.0,15150.0,3202.0,699.0,"Census Tract 6305, Cook County, Illinois",031,17,630500
3,29.9,2307.0,4.0,800.0,448.0,185.0,13.0,706.0,89.0,32.0,...,0.0,767.0,24972.0,11572.0,1020.0,547.0,"Census Tract 6111, Cook County, Illinois",031,17,611100
4,29.9,3298.0,0.0,1289.0,545.0,291.0,115.0,701.0,60.0,64.0,...,0.0,1398.0,35016.0,11113.0,1465.0,625.0,"Census Tract 6114, Cook County, Illinois",031,17,611400

In [6]:
census_pd.to_csv('../analysis_data/census_data.csv')